name: Build and Publish VS Code Extension

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: vscode-extension/package-lock.json
    
    - name: Install dependencies
      run: |
        cd vscode-extension
        npm ci
    
    - name: Compile TypeScript
      run: |
        cd vscode-extension
        npm run compile
    
    - name: Run tests
      run: |
        cd vscode-extension
        npm test
    
    - name: Package extension
      run: |
        cd vscode-extension
        npm install -g @vscode/vsce
        vsce package
    
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v3
      with:
        name: extension-vsix
        path: vscode-extension/*.vsix

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: vscode-extension/package-lock.json
    
    - name: Install dependencies
      run: |
        cd vscode-extension
        npm ci
    
    - name: Compile and package
      run: |
        cd vscode-extension
        npm run compile
        npm install -g @vscode/vsce
        vsce package
    
    - name: Publish to VS Code Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: |
        cd vscode-extension
        vsce publish --pat $VSCE_PAT
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this release
          - Automated release from CI/CD
          
          ## Installation
          Download the VSIX file and install manually, or install from VS Code Marketplace.
        draft: false
        prerelease: false
    
    - name: Upload VSIX to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: vscode-extension/cody-ai-assistant-${{ github.ref_name }}.vsix
        asset_name: cody-ai-assistant-${{ github.ref_name }}.vsix
        asset_content_type: application/zip
